### ISSUE TITLE
Possible error in sidebar.scss

### ISSUE THREAD

**Issue by mattwaler** [kylelogue/mustard-ui#1]
Hello! I'm the guy from reddit who commented about how awesome this is. I've been picking it apart and playing with it myself.

I converted the files into SASS as I prefer the indented syntax over the SCSS, and on render, I'm getting this warning below. Looking at the code, it looks like the "li" selector in sidebar.scss is empty. Is this intended, or are the "a" elements supposed to be nested under it?

Thanks!

![screen shot 2018-04-05 at 9 16 42 am](https://user-images.githubusercontent.com/32300026/38368065-4f703252-38b2-11e8-9fe5-5fd6e62f05bb.png)

![screen shot 2018-04-05 at 9 18 45 am](https://user-images.githubusercontent.com/32300026/38368095-5d3df7fc-38b2-11e8-888e-3a05ba01b717.png)

**Comment by kylelogue** [comment]
Good catch! It's an error fixed by this commit: 9852658ab4a45f95e961633605deff7533fab9e8
