### ISSUE TITLE
Basic keyboard accessibility

### ISSUE THREAD

**Issue by patrickhlauke** [kylelogue/mustard-ui#10]
Beyond the basic styling fix https://github.com/kylelogue/mustard-ui/pull/9 (which only provides minimal styling, and may need to be revisited in future to strengthen some of those styles further to make them more apparent), there are a few more things to consider for keyboard users (looking over the documentation):

- Modals: these will require additional JavaScript to handle correct focus management; when modal is opened, focus should move into the modal; focus should remain in the modal; when the modal is closed, focus should return to the point where it was before the modal was opened.
- Navigation: the hamburger as implemented is not keyboard-focusable (it's an anchor, which does not receive focus by default). simplest way to fix this: use a `<button>` instead; otherwise, will require the addition of `tabindex="0"` (to force focusability), `role="button"` (to convey at least that it's a button to assistive technologies), and JavaScript that reacts not just to `click` but also to `onkeyup` and checks for use of `SPACE` key.
- Sidebars: similar to the Navigation issue, using `<h3>` or similar non-interactive elements is problematic. again, simplest to use a `<button>` (and, at a stretch, this could be nested inside the heading, so `<h3><button> ... </button></h3>`). or use similar additions (`tabindex` etc) as above.
- Tooltips: `<span>`s aren't focusable. at a bare minimum, force focusability with `tabindex="0"`.

There are further things that should be done (with extra `aria-*` attributes) to convey things better to assistive technologies, but getting keyboard access right would be a good first step.

**Comment by kylelogue** [comment]
This is not within the scope of this framework.
