### ISSUE TITLE
How to add abilities to the buttons

### ISSUE THREAD

**Issue by Droobledores** [kylelogue/mustard-ui#11]
Sorry! I am a newbie at ![HTML5](https://raw.githubusercontent.com/encharm/Font-Awesome-SVG-PNG/master/black/png/16/html5.png) and ![CSS3](https://raw.githubusercontent.com/encharm/Font-Awesome-SVG-PNG/master/black/png/16/css3.png), but is there any way to add functions (Let's say, add a link) to the buttons?

**Comment by kylelogue** [comment]
If you use `<a class="button button-primary" href="#">Button Text</a>` you can format a link to look like a button.

**Comment by Droobledores** [comment]
Could there be any way to do that, but with JavaScript?
