### ISSUE TITLE
No styling for HTML5 input types

### ISSUE THREAD

**Issue by optikfluffel** [kylelogue/mustard-ui#15]
Using any of the HTML5 input types (e.g. `<input type="email">`) breaks the wonderful styling of the form input elements. Here's a list of them, according to [w3schools.com](https://www.w3schools.com/html/html_form_input_types.asp):

- color
- date
- datetime-local
- email
- month
- number
- range
- search
- tel
- time
- url
- week

I can see that it's probably not that easy to support all of them right away, but the ones basically staying a text input should work, I guess.

**Comment by francescobianco** [comment]
This is a proposal for the solution
https://github.com/kylelogue/mustard-ui/pull/17
@kylelogue @optikfluffel

**Comment by cssworkshop** [comment]
Fixed in https://github.com/kylelogue/mustard-ui/commit/146fc0a58969b64f03d0e9398ddae58ec5809747
