### ISSUE TITLE
Pre-load costants in style.scss entrypoint

### ISSUE THREAD

**Issue by francescobianco** [kylelogue/mustard-ui#16]
Hi! @kylelogue 

a question for you...
When In use M-UI into Scss Webpack environment I want to do this

```scss
$nav-bg-color: $color-brown-50;
@import 'node_modules/mustard-ui/src/scss/mustard-ui.scss';
```

But I can't because it say me:

```bash
ERROR in ./assets/sass/style.scss
Module build failed: ModuleBuildError: Module build failed: 
$nav-bg-color: $color-brown-50;
              ^
      Undefined variable: "$color-brown-50".
```
We need to split the library into two different pieces 
1. Constants pre-loading
2. Elements and Components 

In this way we can do:
```scss
@import 'node_modules/mustard-ui/src/scss/mustard-ui-constants.scss';

$nav-bg-color: $color-brown-50;
@import 'node_modules/mustard-ui/src/scss/mustard-ui-elements.scss';
@import 'node_modules/mustard-ui/src/scss/mustard-ui-components.scss';
```

Please create a way to do this in a Mustard manner...
In my opinion, this would be the way to keep Mustard-UI as dependency on other projects without necessarily modifying the kernel

**Comment by kylelogue** [comment]
So let me know if this would fix the issue...  You could write the code like this:

```
@import 'node_modules/mustard-ui/src/scss/colors.scss'
$nav-bg-color: $color-brown-50;
@import 'node_modules/mustard-ui/src/scss/mustard-ui.scss';
```

What do you think?

**Comment by francescobianco** [comment]
It works!? (adding subfolder vars)
```scss
@import 'node_modules/mustard-ui/src/scss/vars/colors.scss'
$nav-bg-color: $color-brown-50;
@import 'node_modules/mustard-ui/src/scss/mustard-ui.scss';
```
But, in this way the file was imported multiple times, the second inside mustard-ui.scss
I do not know if this could become a future problem?
