### ISSUE TITLE
Combine config variables into a single defaults file

### ISSUE THREAD

**Issue by dijitaltrix** [kylelogue/mustard-ui#20]
Firstly thanks for releasing this it's good to see a new lightweight bottom - up css framework.

Like many others I've become used to Bootstrap and therefore having a single config file to tweak the css options.

I've created an example fork (https://github.com/dijitaltrix/mustard-ui) which pulls out all the variables into a single config file called 'vars/defaults.scss', this file is loaded by the main 'mustard-ui.scss' file, then another file is called with my specific site overrides which contains specific overrides of defaults.scss.

Personally I prefer this approach over mingling config in with the rest of the css, e.g. it helps when updating older sites as I can pull future changes knowing that my config will not be affected.

As long as the defaults file is always kept up to date the build should never fail due to missing variables, and I can refer to changes in that file to see whats new. 

If it looks okay I'm happy to create a pull request.

**Comment by kylelogue** [comment]
Go for it!

**Comment by TrackTik-Oliver** [comment]
Nicely done, @dijitaltrix . I was frustrated with the $color-* variables being used everywhere. We only have need for a small-ish palette, so trying to determine which colors are used and which aren't was a bit of a pain (not a huge pain, ctrl-shift-f is your friend). This helps a lot. Thanks!

**Comment by kylelogue** [comment]
Closed as this is a personal preference.  Fork this repo to implement as suggested.
