### ISSUE TITLE
Support for :invalid pseudo class

### ISSUE THREAD

**Issue by sprat** [kylelogue/mustard-ui#23]
I would like to use the HTML5 validation API to validate my input fields but I noticed there's no design for `:invalid` fields whereas there is an `.invalid` class that seems to play the same role. Can you please add some design for `:invalid` fields also?

**Comment by cssworkshop** [comment]
https://github.com/kylelogue/mustard-ui/commit/6644b996ae3ec405a31bcf58d12e98c9a26d4422
