### ISSUE TITLE
.mobile-menu missing

### ISSUE THREAD

**Issue by mike-ward** [kylelogue/mustard-ui#25]
Is it my imagination or is `.mobile-menu` missing from the distribution? Trying to use it as the docs say but the menu is not hidden on the desktop. Did a `grep` on the distribution and didn't find it.  I see on the Mustard site that `.mobile-menu` is defined but not in my `npm` distro.

```
grep -r .mobile-menu *
components/navigation.scss:.mobile-menu-toggle {
```
![image](https://user-images.githubusercontent.com/567927/50099824-fc668e80-01ec-11e9-9251-401b0b481670.png)

**Comment by dmarkrollins** [comment]
I had the same question.

So I've added https://github.com/kylelogue/mustard-ui/pull/26

**Comment by dmarkrollins** [comment]
I think you also need this:

.mobile-menu {
    display: none;
    position: absolute;
    top: 15px;
    right: 30px;
    z-index: 10;
}

**Comment by kylelogue** [comment]
Pull request has been merged.
