### ISSUE TITLE
support .display-lg-up for th/td ?

### ISSUE THREAD

**Issue by mh-cbon** [kylelogue/mustard-ui#27]
On firefox 66.05 when i use the `.display-lg-up` class on `tr/td` it defines `display:initial` for large screens. 

That break the display, for some reasons the cells behaves like if they had `display:inline`, and their baseline is like `top`.

How do you hide columns for some viewport dimensions otherwise ?

**Comment by kylelogue** [comment]
This is not considered a good practice in web dev.
