### ISSUE TITLE
How to compile scss files into a new css?

### ISSUE THREAD

**Issue by k0fi** [kylelogue/mustard-ui#28]
Hello,
How can I modify mustard-ui through from src/*.css files? 
I have encountered 2 problems while trying the whole project into a new mustard-ui.css:
1. The imports are are not complete. So for example `base.scss` does not import `@import '../vars/colors';` so get error in vscode's Live sass watch. 
2. even afeter importing relevant code, it is not clear how to make a final   `mustard-ui.css` out of updated .scss  
Appreciate your hints about this.

**Comment by kylelogue** [comment]
`npm install` from the command line
`npm install -g gulp`
then run `gulp` from the command line.  Google gulp and take a look at the gulpfile for more questions.
