### ISSUE TITLE
Missing dropdown arrow on select lists

### ISSUE THREAD

**Issue by tpow** [kylelogue/mustard-ui#29]
The dropdown arrow using SVG with a data URL works on current Safari, but is invisible on older versions of Firefox and Chrome. This causes usability issues because it looks exactly like the text box in this case. It is more important to have the dropdown arrow than to have the simplistic style.

**Comment by cssworkshop** [comment]
Fixed in https://github.com/kylelogue/mustard-ui/commit/146fc0a58969b64f03d0e9398ddae58ec5809747
