### ISSUE TITLE
Make `gulp serve` do something useful

### ISSUE THREAD

**Issue by chilts** [kylelogue/mustard-ui#3]
I just forked the project and sent a PR (#2) and while I was playing I noticed something.

Running an `npm install` was fine, then I ran the following:

```
$ node_modules/.bin/gulp 
[23:15:12] Using gulpfile ~/src/chilts/mustard-ui/gulpfile.js
[23:15:12] Starting 'serve'...
[23:15:12] Finished 'serve' after 24 ms
[23:15:12] Starting 'sass'...
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.20.16:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.20.16:3001
 --------------------------------------
[Browsersync] Serving files from: ./
[Browsersync] 2 files changed (mustard-ui.min.css.map, mustard-ui.min.css)
[23:15:12] Finished 'sass' after 303 ms
[23:15:12] Starting 'default'...
[23:15:12] Finished 'default' after 17 μs
```

(Side note: I don't have gulp installed globally, so just found that one in my `node_modules`. I'm also happy to write a few notes down for contributors, esp. since I'm not sure this is how you're currently doing it ... let me know and I'll open another issue and send a fix.)

Anyway, back onto my main thought. I saw that the default action in the `gulpfile.js` called `serve`, so I opened localhost:3000 to see what was there. Nothing at the moment. So I tried to load up `http://localhost:3000/mustard-ui.min.css` but still nothing. In the end I realised I needed `http://localhost:3000/dist/css/mustard-ui.min.css` to show the css.

However, this told me that the gulp server was actually serving up the repo dir (I checked http://localhost:3000/package.json` and it loaded fine) so, whilst there is nothing *bad* about this, it seemed like a small opportunity to serve up something else - maybe a small page which loads up the CSS files. 

Or if we don't want to, perhaps just remove the `serve` target? I'd love to know if you actually use it because if you do, I've missed the point entirely (for which I apologise)! :turkey:

**Comment by chilts** [comment]
And yeah, whether the gulp `serve` command can use a different root rather than the current dir, isn't something I know at the moment, but could be good (perhaps `dist/`, an `index.html` file in there would be cool, but also might be messy).

This ticket is just to mull things over. You might not like it, but you might think there is something in it somewhere. :smiley:

**Comment by kylelogue** [comment]
Keep it coming.  I like your ideas.

I commented on your other issue about putting together an example site so people pulling the repo via npm can actually see something going on once you run gulp.  I'm gonna try to whip something up this morning.

**Comment by kylelogue** [comment]
So I changed the npm scripts so that they work using the local gulp installation and now it does something much cooler now.  See 297fce0da67f4ef3f855a1361c17f605a7c6ace1

**Comment by chilts** [comment]
The new `npm run build` stuff is great. Thank you.
