### ISSUE TITLE
Documentation site is offline.

### ISSUE THREAD

**Issue by aashish-kumar-e3203** [kylelogue/mustard-ui#31]
https://mustard-ui.com/ cannot be reached. Has it been moved to a different place.

**Comment by Bublikus** [comment]
+1
You have a great design! Please, make your site reachable.

**Comment by Ameliaaaaaa** [comment]
You can visit an archive of it here: https://web.archive.org/web/20190627093317/https://mustard-ui.com/

**Comment by kylelogue** [comment]
The documentation has been moved to https://kylelogue.github.io/mustard-ui and is now also included in the repo
