### ISSUE TITLE
hidden “hamburger” 

### ISSUE THREAD

**Issue by rcousins89** [kylelogue/mustard-ui#37]
Hi Kyle,

I am having an issue when resizing my browser, the hamburger appears but when i click it nothing appears within it. I made a test case and copied and pasted your exact nav bar but still didnt work. Am i missing something.

Thanks

**Comment by kylelogue** [comment]
This is a CSS only framework, you'll need to implement your own Javascript to get this type of functionality.  I'm using jQuery to show/hide the menu.
