### ISSUE TITLE
Mustard-UI extensions/base classes and more configurable

### ISSUE THREAD

**Issue by elbakerino** [kylelogue/mustard-ui#38]
Hi Folks!

i got a request to build some AMP stuff, after evaluation I found that mustard-ui is a great (and not abandoned) base solution.

For me a few features are missing, like:
- spacing classes like [basscss](https://basscss.com/#basscss-margin) has
- configurable space / spacings  
- available modifier `.dense` for some stuff like panels (or also not, because can be done with gutter-classes, personally i like `&.dense`, but for CSS size no gutters at all would be better)
- font-sizes use em/rem instead of px
- further display and alignment classes (`display: flex`, `align-items: center` etc.)
- disable attachment to native elements (e.g. button styles applied only to class `.btn` instead of `.button, button`)
  - this leads to configurable css selectors
- loading (not only progress)
- reusable typography selectors (body style also as `body1`, slightly smaller version as `body2`)
- more typography like `$font-family-mono`

Also i needed to change some default gutters, removed some top/bottom from e.g. `blockquote` as this would be variants and not the base for me.

This of cause would increase the over-all size (especially if adding responsive gutters (~8628bytes). Also some changes i made would maybe destroy existing designs.

For the AMP testing and evaluation i begun the changes in my forks branch scribbles. Not everything is done, like said, it is just for some evaluation: https://github.com/elbakerino/mustard-ui/tree/scribbles

(Most) changes are documented in the [README_FORK.md](https://github.com/elbakerino/mustard-ui/blob/scribbles/README_FORK.md)

I'm happy to create forks for features wanted or also to discuss some concept stuff - if you are open for it! If not, and i need to further work on it, i would revive an old (way too big and ugly) css framework i started and releasing the combined changes (after finalizing). Otherwise if Mustard get's most features I can simply build an add-on lib, compatible with mustards configs.

Cheers, michael

**Comment by kylelogue** [comment]
This framework is meant to be a customizable starting point, not a final solution.  Adding these would only bloat the framework.  Please fork to implement these features.
