### ISSUE TITLE
Domain not responding

### ISSUE THREAD

**Issue by tpow** [kylelogue/mustard-ui#42]
In case it isn't a temporary failure, I thought I would note that the [mustard-ui.com](https://mustard-ui.com) domain is not responding.

Did you decide to use [https://kylelogue.github.io/mustard-ui](https://kylelogue.github.io/mustard-ui) on GitHub  instead?

If so, you will want to update the CSS and CDN to have the new URL embedded in the css file.

**Comment by kylelogue** [comment]
Resolved
