### ISSUE TITLE
Range input slider styling

### ISSUE THREAD

**Issue by fitztrev** [kylelogue/mustard-ui#43]
The form styling for an `<input type="range">` is appearing like this.

Actual:

![image](https://user-images.githubusercontent.com/271432/91191002-3c6c5d00-e6c2-11ea-8a6b-22bf76864d23.png)

Expected:

![image](https://user-images.githubusercontent.com/271432/91191073-50b05a00-e6c2-11ea-864b-32450d7a2b56.png)

**Comment by kylelogue** [comment]
Range inputs are not supported.
