### ISSUE TITLE
Lot of deprecations from sass

### ISSUE THREAD

**Issue by zgoda** [kylelogue/mustard-ui#49]
When using `dart-sass` (1.37.5) to compile scss there's a lot of deprecation warnings:

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($i, $col-count)

More info and automated migrator: https://sass-lang.com/d/slash-div
```

**Comment by kylelogue** [comment]
This project explicitly supports gulp using the included `gulpfile.js`.  No support for `dart-sass` has been planned.
