### ISSUE TITLE
[question] Code for the https://mustard-ui.com/ site

### ISSUE THREAD

**Issue by chilts** [kylelogue/mustard-ui#5]
Hi Kyle,

Sorry to be a pain with these tickets and PRs - presumably while you're sleeping! Anyway, I was just wondering where the code is for the mustard-ui.com site, and if it is or will be made available?

I looked for another branch in the repo which might be it but couldn't see anything. And I couldn't see anything in the main repo ... but perhaps my eyes are deceiving me since it's almost midnight. Thanks for your help.

Andy

**Comment by kylelogue** [comment]
This kind of stuff is literally my oxygen.  I love it.  So don't feel like you're a bother.

The current website is built using wordpress which I don't know that people would want all that source code.  I can however put together an html only example site that utilizes a lot of these components that launches when you spin up gulp.  It would let you tweak some of the variables and see them update in real time in your browser.

**Comment by kylelogue** [comment]
I've added some goodies to `npm run dev` via 297fce0da67f4ef3f855a1361c17f605a7c6ace1
