### ISSUE TITLE
Doc(flexbox-grid) Errata

### ISSUE THREAD

**Issue by JohnNiang** [kylelogue/mustard-ui#7]
https://mustard-ui.com/docs/flexbox-grid/

 > ```Use an offset ```section

```
.col-sm-4          .col-sm-offset-2
```
should be 
```
.col-sm-5          .col-sm-offset-2
```

**Comment by kylelogue** [comment]
Nice catch!  Thanks for taking a detailed look at things.  I've fixed this issue.
